/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ArtistMembersContract
  extends Truffle.Contract<ArtistMembersInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ArtistMembersInstance>;
}

export interface ArtistAdd {
  name: "ArtistAdd";
  args: {
    artistAddress: string;
    0: string;
  };
}

export interface OwnershipTransferred {
  name: "OwnershipTransferred";
  args: {
    previousOwner: string;
    newOwner: string;
    0: string;
    1: string;
  };
}

type AllEvents = ArtistAdd | OwnershipTransferred;

export interface ArtistMembersInstance extends Truffle.ContractInstance {
  /**
   * Returns the address of the current owner.
   */
  owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
   */
  renounceOwnership: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  transferOwnership: {
    (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  addArtist: {
    (
      _address: string,
      _name: string,
      _iconURL: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _address: string,
      _name: string,
      _iconURL: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      id: BN;
      artistAddress: string;
      name: string;
      iconURL: string;
    }>;
    sendTransaction(
      _address: string,
      _name: string,
      _iconURL: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _address: string,
      _name: string,
      _iconURL: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  checkIsArtistExist(
    _address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  getArtistSize(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  getArtistById(
    id: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ id: BN; artistAddress: string; name: string; iconURL: string }>;

  getArtistByAddress(
    _address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ id: BN; artistAddress: string; name: string; iconURL: string }>;

  getAllArtists(
    txDetails?: Truffle.TransactionDetails
  ): Promise<
    { id: BN; artistAddress: string; name: string; iconURL: string }[]
  >;

  methods: {
    /**
     * Returns the address of the current owner.
     */
    owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership: {
      (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    addArtist: {
      (
        _address: string,
        _name: string,
        _iconURL: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _address: string,
        _name: string,
        _iconURL: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<{
        id: BN;
        artistAddress: string;
        name: string;
        iconURL: string;
      }>;
      sendTransaction(
        _address: string,
        _name: string,
        _iconURL: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _address: string,
        _name: string,
        _iconURL: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    checkIsArtistExist(
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    getArtistSize(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    getArtistById(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      id: BN;
      artistAddress: string;
      name: string;
      iconURL: string;
    }>;

    getArtistByAddress(
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      id: BN;
      artistAddress: string;
      name: string;
      iconURL: string;
    }>;

    getAllArtists(
      txDetails?: Truffle.TransactionDetails
    ): Promise<
      { id: BN; artistAddress: string; name: string; iconURL: string }[]
    >;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
