/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ArtProjectsContract
  extends Truffle.Contract<ArtProjectsInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ArtProjectsInstance>;
}

export interface OwnershipTransferred {
  name: "OwnershipTransferred";
  args: {
    previousOwner: string;
    newOwner: string;
    0: string;
    1: string;
  };
}

type AllEvents = OwnershipTransferred;

export interface ArtProjectsInstance extends Truffle.ContractInstance {
  /**
   * Returns the address of the current owner.
   */
  owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
   */
  renounceOwnership: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  transferOwnership: {
    (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  addProject: {
    (
      _artistAddress: string,
      _name: string,
      _description: string,
      _targetFundingAmount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _artistAddress: string,
      _name: string,
      _description: string,
      _targetFundingAmount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _artistAddress: string,
      _name: string,
      _description: string,
      _targetFundingAmount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _artistAddress: string,
      _name: string,
      _description: string,
      _targetFundingAmount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  addFunderAmount: {
    (
      projectId: number | BN | string,
      _investorAddress: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      projectId: number | BN | string,
      _investorAddress: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      projectId: number | BN | string,
      _investorAddress: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      projectId: number | BN | string,
      _investorAddress: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  endProject: {
    (
      _address: string,
      projectId: number | BN | string,
      dataURL: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _address: string,
      projectId: number | BN | string,
      dataURL: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _address: string,
      projectId: number | BN | string,
      dataURL: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _address: string,
      projectId: number | BN | string,
      dataURL: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  checkIsAddressAbleToMint(
    projectId: number | BN | string,
    _address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  getAddressShareInProject(
    projectId: number | BN | string,
    _address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  setProjectShareNFTClaimed: {
    (
      projectId: number | BN | string,
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      projectId: number | BN | string,
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      projectId: number | BN | string,
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      projectId: number | BN | string,
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getProjectFunderListByProjectId(
    projectId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  getFundedProjectByAddress(
    _address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN[]>;

  getFundAmountsByProjectId(
    projectId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ funderAddress: string; amount: BN }[]>;

  getAllProjects(
    txDetails?: Truffle.TransactionDetails
  ): Promise<
    {
      id: BN;
      artistAddress: string;
      name: string;
      description: string;
      targetFundingAmount: BN;
      currentFundingAmount: BN;
      totalFunder: BN;
      isOpen: boolean;
      dataURL: string;
    }[]
  >;

  checkIsProjectExist(
    id: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  getProjectSize(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  getProjectById(
    id: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    id: BN;
    artistAddress: string;
    name: string;
    description: string;
    targetFundingAmount: BN;
    currentFundingAmount: BN;
    totalFunder: BN;
    isOpen: boolean;
    dataURL: string;
  }>;

  methods: {
    /**
     * Returns the address of the current owner.
     */
    owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership: {
      (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    addProject: {
      (
        _artistAddress: string,
        _name: string,
        _description: string,
        _targetFundingAmount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _artistAddress: string,
        _name: string,
        _description: string,
        _targetFundingAmount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _artistAddress: string,
        _name: string,
        _description: string,
        _targetFundingAmount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _artistAddress: string,
        _name: string,
        _description: string,
        _targetFundingAmount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    addFunderAmount: {
      (
        projectId: number | BN | string,
        _investorAddress: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        projectId: number | BN | string,
        _investorAddress: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        projectId: number | BN | string,
        _investorAddress: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        projectId: number | BN | string,
        _investorAddress: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    endProject: {
      (
        _address: string,
        projectId: number | BN | string,
        dataURL: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _address: string,
        projectId: number | BN | string,
        dataURL: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _address: string,
        projectId: number | BN | string,
        dataURL: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _address: string,
        projectId: number | BN | string,
        dataURL: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    checkIsAddressAbleToMint(
      projectId: number | BN | string,
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    getAddressShareInProject(
      projectId: number | BN | string,
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    setProjectShareNFTClaimed: {
      (
        projectId: number | BN | string,
        _address: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        projectId: number | BN | string,
        _address: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        projectId: number | BN | string,
        _address: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        projectId: number | BN | string,
        _address: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getProjectFunderListByProjectId(
      projectId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    getFundedProjectByAddress(
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN[]>;

    getFundAmountsByProjectId(
      projectId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ funderAddress: string; amount: BN }[]>;

    getAllProjects(
      txDetails?: Truffle.TransactionDetails
    ): Promise<
      {
        id: BN;
        artistAddress: string;
        name: string;
        description: string;
        targetFundingAmount: BN;
        currentFundingAmount: BN;
        totalFunder: BN;
        isOpen: boolean;
        dataURL: string;
      }[]
    >;

    checkIsProjectExist(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    getProjectSize(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    getProjectById(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      id: BN;
      artistAddress: string;
      name: string;
      description: string;
      targetFundingAmount: BN;
      currentFundingAmount: BN;
      totalFunder: BN;
      isOpen: boolean;
      dataURL: string;
    }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
