/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { ArtistMembersContract } from "./ArtistMembers";
import { ArtProjectsContract } from "./ArtProjects";
import { ElectionV2Contract } from "./ElectionV2";
import { Erc165Contract } from "./Erc165";
import { Erc20Contract } from "./Erc20";
import { Erc721Contract } from "./Erc721";
import { FundRasingShareTokenContract } from "./FundRasingShareToken";
import { Ierc165Contract } from "./Ierc165";
import { Ierc20Contract } from "./Ierc20";
import { Ierc20MetadataContract } from "./Ierc20Metadata";
import { Ierc721Contract } from "./Ierc721";
import { Ierc721MetadataContract } from "./Ierc721Metadata";
import { Ierc721ReceiverContract } from "./Ierc721Receiver";
import { MainGameContract } from "./MainGame";
import { OwnableContract } from "./Ownable";
import { PlatformTokenContract } from "./PlatformToken";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ArtistMembers"): ArtistMembersContract;
      require(name: "ArtProjects"): ArtProjectsContract;
      require(name: "ElectionV2"): ElectionV2Contract;
      require(name: "ERC165"): Erc165Contract;
      require(name: "ERC20"): Erc20Contract;
      require(name: "ERC721"): Erc721Contract;
      require(name: "FundRasingShareToken"): FundRasingShareTokenContract;
      require(name: "IERC165"): Ierc165Contract;
      require(name: "IERC20"): Ierc20Contract;
      require(name: "IERC20Metadata"): Ierc20MetadataContract;
      require(name: "IERC721"): Ierc721Contract;
      require(name: "IERC721Metadata"): Ierc721MetadataContract;
      require(name: "IERC721Receiver"): Ierc721ReceiverContract;
      require(name: "MainGame"): MainGameContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "PlatformToken"): PlatformTokenContract;
    }
  }
}

export { ArtistMembersContract, ArtistMembersInstance } from "./ArtistMembers";
export { ArtProjectsContract, ArtProjectsInstance } from "./ArtProjects";
export { ElectionV2Contract, ElectionV2Instance } from "./ElectionV2";
export { Erc165Contract, Erc165Instance } from "./Erc165";
export { Erc20Contract, Erc20Instance } from "./Erc20";
export { Erc721Contract, Erc721Instance } from "./Erc721";
export {
  FundRasingShareTokenContract,
  FundRasingShareTokenInstance
} from "./FundRasingShareToken";
export { Ierc165Contract, Ierc165Instance } from "./Ierc165";
export { Ierc20Contract, Ierc20Instance } from "./Ierc20";
export {
  Ierc20MetadataContract,
  Ierc20MetadataInstance
} from "./Ierc20Metadata";
export { Ierc721Contract, Ierc721Instance } from "./Ierc721";
export {
  Ierc721MetadataContract,
  Ierc721MetadataInstance
} from "./Ierc721Metadata";
export {
  Ierc721ReceiverContract,
  Ierc721ReceiverInstance
} from "./Ierc721Receiver";
export { MainGameContract, MainGameInstance } from "./MainGame";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { PlatformTokenContract, PlatformTokenInstance } from "./PlatformToken";
