export enum IconButtonType {
    archive = "archive",
    arrowDown = "arrowDown",
    calendar = "calendar",
    copy = "copy",
    cross = "cross",
    flag = "flag",
    home = "home",
    image = "image",
    input = "input",
    list = "list",
    menu = "menu",
    more = "more",
    performance = "performance",
    students = "students",
    task = "task",
    topics = "topics",
    testing = "testing",
}